name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TEST_TAG: spring-boot-docker:gitlab_action

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.TEST_TAG }}
    - name: echo local image
      run: docker images
    - name: docker inspect
      run: docker inspect ${{ env.TEST_TAG }}
    - name: dind inspect
      run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --network=host docker:dind /bin/sh -c docker inspect ${{ env.TEST_TAG }}
    - name: SAS security image scan
      run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --network=host sas-image-scanner-registry.cn-hangzhou.cr.aliyuncs.com/sas_public/sas-image-scanner:latest --accessKeyId=${{ secrets.ACCESSKEYID }} --accessKeySecret=${{ secrets.ACCESSKEYSECRET }} --token=${{ secrets.SAS_TOKEN }} --imageId=${{ env.TEST_TAG }}
